---
apiVersion: "helm.cattle.io/v1"
kind: "HelmChart"
metadata:
  name: "nfs"
  namespace: "default"
spec:
  chart: "nfs-subdir-external-provisioner"
  repo: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
  targetNamespace: "default"
  set:
    nfs.server: "tec-kube-ctl"
    nfs.path: "/exported/path"
    storageClass.name: "nfs"
