kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume  # Sets PV's name
  namespace: sonar
  labels:
    type: local  # Sets PV's type to local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 6Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  namespace: sonar
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 4Gi  # Sets volume size