---
- name: "setup kube worker nodes"
  hosts: "kube_nodes"
  become: true
  become_user: "root"
  vars:
    cmd_file: "/boot/firmware/cmdline.txt"
    k3s_install: "/opt/k3ssetup"
  environment:
    K3S_URL: "https://{{ ctlr_host }}:6443"
    K3S_TOKEN: "{{ cluster_token }}"
  tasks:
    - name: "call common tasks"
      ansible.builtin.import_tasks:
        file: "kube-common.yml"
    - name: "gather service facts"
      ansible.builtin.service_facts: null
    - name: "Download k3s script."
      get_url:
        url: "https://get.k3s.io"
        dest: "{{ k3s_install }}"
        mode: 700
      when: "ansible_facts.services['k3s.service'] is undefined"
    - name: "Install k3s."
      shell: "{{ k3s_install }}"
      when: "ansible_facts.services['k3s.service'] is undefined"
