apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  labels:
    app: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 8Gi  # Sets volume size