apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: jenkins
  labels:
    app: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 4Gi  # Sets volume size