apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../../../../home_server/src/mnt/raid/jenkins/docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: jenkins
  name: jenkins
  namespace: "jenkins"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: jenkins
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/arch"
                    operator: "In"
                    values:
                      - "amd64"
                      - "arm64"
    spec:
      containers:
        - env:
            - name: JENKINS_OPTS
              value: --httpPort=8080
          image: jenkins/jenkins:latest-jdk17
          name: jenkins
          ports:
            - name: web-ui
              containerPort: 8080
              protocol: TCP
            - name: agent
              containerPort: 50000
              protocol: TCP
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
      hostname: jenkins
      restartPolicy: Always
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
