---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jenkins-pvc"
  namespace: "jenkins"
  labels:
    app: "jenkins"
spec:
  storageClassName: "nfs"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
