# not figured out proper PV creation for local-path
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv
#   labels:
#     type: local
# spec:
#   storageClassName: local-path
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - tec-kube-n1
#           - tec-kube-n2
#           - tec-kube-n3
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
  labels:
    app: jenkins
spec:
  # volumeName: jenkins-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi 