apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jenkins-home
  name: jenkins-home
  namespace: "jenkins"
spec:
  storageClassName: "nfs"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "16Gi"
