apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../../../../home_server/src/mnt/raid/jenkins/docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: jenkins
  name: jenkins
  namespace: "jenkins"
spec:
  type: "LoadBalancer"
  ports:
    - name: "web-ui"
      port: 8080
      targetPort: 8080
    - name: "agent"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: jenkins
