apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sonar
  labels:
    app: postgres
data:
  POSTGRES_DB: sonar_db
  POSTGRES_USER: sonar_user
  POSTGRES_PASSWORD: S0N4RQUB3