---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "postgres-pvc"
  namespace: "sonar"
  labels:
    app: "postgres"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
