# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv
#   namespace: sonar
#   labels:
#     app: postgres
# spec:
#   storageClassName: local-path
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: "/mnt/kube/sonar/sq"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: sonar
  labels:
    app: postgres
spec:
  # volumeName: postgres-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi 