apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgresql
  name: postgresql
  namespace: "sonar"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn  # Explicitly specify Longhorn StorageClass
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgresql-data
  name: postgresql-data
  namespace: "sonar"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn  # Explicitly specify Longhorn StorageClass
  resources:
    requests:
      storage: 16Gi