apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sonarqube-data
  name: sonarqube-data
  namespace: "sonar"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sonarqube-extensions
  name: sonarqube-extensions
  namespace: "sonar"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sonarqube-logs
  name: sonarqube-logs
  namespace: "sonar"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
