---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "sonar-pvc"
  namespace: "sonar"
spec:
  storageClassName: "nfs"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
