kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-pv  # Sets PV's name
  namespace: sonar
  labels:
    type: local  # Sets PV's type to local
    app: sonar
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-pvc
  namespace: sonar
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
