# https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nfs-mount-on-ubuntu-20-04
---
- name: "install nfs server and create shares"
  hosts: "kube_controller"
  become: true
  become_user: "root"
  vars:
    base_dir: "/mnt/storage/nfs"
    config_file: "/etc/exports"
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "apt install nfs server package"
      apt:
        name: "nfs-kernel-server"
        state: "present"
    - name: "Create cluster directory if it does not exist"
      ansible.builtin.file:
        path: "{{ base_dir }}/cluster"
        owner: nobody
        group: nogroup
        state: "directory"

        mode: "0777"
    - name: "add node shares"
      blockinfile:
        state: "present"
        insertafter: "EOF"
        dest: "{{ config_file }}"
        marker: "# {mark} _NODE_SHARES_"
        append_newline: true
        prepend_newline: true
        content:
          "{{ base_dir }}/cluster *(rw,all_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)\n"
    - name: "export nfs shares"
      command: "exportfs -ra"
    - name: "reload nfs server"
      ansible.builtin.systemd_service:
        state: "restarted"
        daemon_reload: true
        name: "nfs-kernel-server"
    - name: "Copy nfs helm chart"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../helm/nfs.yml"
        dest: "/var/lib/rancher/k3s/server/manifests/nfs.yml"
        mode: "0600"
    - name: "reload k3s server"
      ansible.builtin.systemd_service:
        state: "restarted"
        daemon_reload: true
        name: "k3s"
